development:
  adapter: postgresql
  encoding: unicode
  database: gig_surfing_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: gig_surfing_test
  pool: 5
  username: kellywaters
  password: 